---

- hosts: all
  become: yes
  tasks:
    - name: Add ruki user
      user:
        name: ruki
        password: !
        comment: PaaS access
        group: www-data

    - name: Install Python packages
      pip:
        executable: pip3
        name: ['ruki', 'uwsgi']
      register: packages_installed

    - shell: which uwsgi
      register: uwsgi_location
      when: packages_installed is changed

    - name: Create uwgsi symlink
      file:
        src: "{{uwsgi_location.stdout}}"
        dest: /usr/local/bin/uwsgi-ruki
        owner: root
        group: root
        state: link
      when: packages_installed is changed

    - name: Install uwsgi dist script
      get_url:
        url: https://raw.githubusercontent.com/mardix/ruki/master/files/uwsgi-ruki.dist
        dest: /etc/init.d/uwsgi-ruki
        mode: 0700
      when: packages_installed is changed

    - name: Install uwsgi-ruki dist script
      shell: update-rc.d uwsgi-ruki defaults
      args:
        creates: /etc/rc2.d/S01uwsgi-ruki
      when: packages_installed is changed


    - name: Install uwsgi-ruki systemd script
      get_url:
        url: https://raw.githubusercontent.com/mardix/ruki/master/files/uwsgi-ruki.service
        dest: /etc/systemd/system/uwsgi-ruki.service
        mode: 0600
      when: packages_installed is changed

    - name: Create ruki ansible tmp dir
      file:
        path: ~ruki/.ansible/tmp
        mode: 0700
        owner: ruki
        group: www-data
        state: directory

- hosts: all
  become: yes
  become_user: ruki
  tasks:

    - name: Copy up my SSH key for ruki
      copy: src=~/.ssh/id_rsa.pub dest=/tmp/id_rsa.pub

    - name: Ask ruki to use SSH key
      shell: ruki set-ssh /tmp/id_rsa.pub
      args:
        creates: ~/.ssh/authorized_keys

- hosts: all
  become: yes
  tasks:

    - name: Test if systemctl is present
      shell: command -v systemctl
      register: systemctl

    - name: Enable uwsgi-ruki service
      systemd:
        name: uwsgi-ruki
        enabled: yes
        state: started
        masked: no
      when: '"systemctl" in systemctl.stdout'

    - name: Start uwsgi init script
      service:
        name: uwsgi-ruki
        state: started
      when: '"systemctl" not in systemctl.stdout'

    - name: Get nginx default config
      get_url:
        url: https://raw.githubusercontent.com/mardix/ruki/master/files/nginx.conf
        dest: /etc/nginx/sites-available/default
        force: yes
      register: nginx_config_installed

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
      when: nginx_config_installed is changed

    - name: Get incron config
      get_url:
        url: https://raw.githubusercontent.com/mardix/ruki/master/files/incron.conf
        dest: /etc/incron.d/ruki
      register: incron_config_installed

    - name: Restart incron service
      service:
        name: incron
        state: restarted
      when: incron_config_installed is changed